/* Image 2.0 妖怪圖像資產表。尚未生成者由 game.js 暫時沿用程序像素圖。 */
(function () {
  'use strict';
  window.GameData = window.GameData || {};
  window.GameData.MONSTER_IMAGE_MAP = {
    moss_horn: 'assets/monsters/moss_horn.webp',
    lamp_fox: 'assets/monsters/lamp_fox.webp',
    ink_cat: 'assets/monsters/ink_cat.webp',
    moon_deer: 'assets/monsters/moon_deer.webp',
    rock_tapir: 'assets/monsters/rock_tapir.webp',
    mist_hound: 'assets/monsters/mist_hound.webp',
    red_sparrow: 'assets/monsters/red_sparrow.webp',
    reed_owl: 'assets/monsters/reed_owl.webp',
    cloud_swallow: 'assets/monsters/cloud_swallow.webp',
    dawn_crane: 'assets/monsters/dawn_crane.webp',
    night_bat: 'assets/monsters/night_bat.webp',
    rain_kite: 'assets/monsters/rain_kite.webp',
    rain_frog: 'assets/monsters/rain_frog.webp',
    thunder_turtle: 'assets/monsters/thunder_turtle.webp',
    mirror_carp: 'assets/monsters/mirror_carp.webp',
    mist_eel: 'assets/monsters/mist_eel.webp',
    mud_loach: 'assets/monsters/mud_loach.webp',
    ember_crab: 'assets/monsters/ember_crab.webp',
    dandelion_spirit: 'assets/monsters/dandelion_spirit.webp',
    ember_mushroom: 'assets/monsters/ember_mushroom.webp',
    dew_sprout: 'assets/monsters/dew_sprout.webp',
    stone_root: 'assets/monsters/stone_root.webp',
    sun_blossom: 'assets/monsters/sun_blossom.webp',
    shadow_vine: 'assets/monsters/shadow_vine.webp',
    ghost_lamp: 'assets/monsters/ghost_lamp.webp',
    paper_wraith: 'assets/monsters/paper_wraith.webp',
    well_echo: 'assets/monsters/well_echo.webp',
    ash_wraith: 'assets/monsters/ash_wraith.webp',
    grave_moss: 'assets/monsters/grave_moss.webp',
    dawn_bell_soul: 'assets/monsters/dawn_bell_soul.webp',
    bronze_doll: 'assets/monsters/bronze_doll.webp',
    stone_beetle: 'assets/monsters/stone_beetle.webp',
    wind_clock_bird: 'assets/monsters/wind_clock_bird.webp',
    water_clock_beast: 'assets/monsters/water_clock_beast.webp',
    furnace_gear_lion: 'assets/monsters/furnace_gear_lion.webp',
    moon_mirror_guard: 'assets/monsters/moon_mirror_guard.webp',
    sj_shengsheng: 'assets/monsters/sj_shengsheng.webp',
    sj_lushu: 'assets/monsters/sj_lushu.webp',
    sj_xuangui: 'assets/monsters/sj_xuangui.webp',
    sj_lu_fish: 'assets/monsters/sj_lu_fish.webp',
    sj_ninetail: 'assets/monsters/sj_ninetail.webp',
    sj_chiru: 'assets/monsters/sj_chiru.webp',
    sj_changyou: 'assets/monsters/sj_changyou.webp',
    sj_gudiao: 'assets/monsters/sj_gudiao.webp',
    sj_quru: 'assets/monsters/sj_quru.webp',
    sj_fenghuang: 'assets/monsters/sj_fenghuang.webp',
    sj_zhuyan: 'assets/monsters/sj_zhuyan.webp',
    sj_yingzhao: 'assets/monsters/sj_yingzhao.webp',
    sj_luwu: 'assets/monsters/sj_luwu.webp'
  };
})();
